CREATE TABLE IF NOT EXISTS beans (
    BeansID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 START 100)
    , BeansProcess VARCHAR(64)
    , BeanQScore REAL
    , FarmID INT NOT NULL REFERENCES farm
    , BeansOrderID INT NOT NULL REFERENCES beansorder
)