CREATE TABLE IF NOT EXISTS beansorder (
    BeansOrderID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 START 100)
    , BeansOrderQty INT NOT NULL
    , BeansOrderUnitWeight_lb REAL NOT NULL
    , OrderID INT NOT NULL REFERENCES order
)