CREATE TABLE IF NOT EXISTS burr (
    BurrID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 START 100)
    , BurrSize_mm REAL NOT NULL
    , BurrMaterial VARCHAR(32) NOT NULL
    , BurrMake VARCHAR(64) NOT NULL
    , BurrModel VARCHAR(64) NOT NULL
)