CREATE TABLE IF NOT EXISTS farm (
    FarmID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 START 100)
   , FarmName VARCHAR(128) NOT NULL UNIQUE
   , FarmCity VARCHAR(64) NOT NULL
   , FarmCountry VARCHAR(64) NOT NULL
   , FarmElevation REAL
)