CREATE TABLE IF NOT EXISTS grinder (
    GrinderID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 START 100)
    , GrinderMake VARCHAR(64) NOT NULL
    , GrinderModel VARCHAR(64) NOT NULL
    , GrinderType VARCHAR(64) NOT NULL
    , BurrID INT NOT NULL REFERENCES burr
)