CREATE TABLE IF NOT EXISTS order (
    OrderID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 START 100)
   , OrderQty INT NOT NULL
   , OrderDate DATE NOT NULL
   , OrderShipDate DATE NOT NULL
   , OrderReceivedDate DATE NOT NULL
   , SupplierID INT NOT NULL REFERENCES supplier
)