CREATE TABLE IF NOT EXISTS supplier (
    SupplierID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 START 100)
    , SupplierName VARCHAR(128) NOT NULL UNIQUE
    , SupplierCity VARCHAR(64) NOT NULL
    , SupplierState VARCHAR(64) NOT NULL
    , SupplierCountry VARCHAR(64) NOT NULL
)