CREATE TABLE IF NOT EXISTS varietal (
    VarietalID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 START 100)
   , VarietalName VARCHAR(64) NOT NULL UNIQUE
   , CoffeeID INT REFERENCES coffee
)